name: CI - Testes Mocha

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 12 * * *'

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Diagnóstico
        run: |
          node -v
          npm -v
          ls -la node_modules/.bin

      - name: Executar testes
        run: node ./node_modules/mocha/bin/mocha.js

      - name: Gerar relatório
        run: |
          mkdir -p relatorios
          node ./node_modules/mocha/bin/mocha.js --reporter json > relatorios/resultado-testes.json

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: relatorios/resultado-testes.json